export const WORKER_STATUS = {
  CREATED: 0,
  STARTED: 1,
  RUNNING: 2,
  EXITED: 3
}

export const WORKER_STATUS_STR = {
  [WORKER_STATUS.CREATED]: 'CREATED',
  [WORKER_STATUS.STARTED]: 'STARTED',
  [WORKER_STATUS.RUNNING]: 'RUNNING',
  [WORKER_STATUS.EXITED]: 'EXITED'
}
